//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Is_Havuzu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Is_Havuzu()
        {
            this.tbl_Is = new HashSet<tbl_Is>();
        }
    
        public int intIsId { get; set; }
        public int intGrupId { get; set; }
        public string strAd { get; set; }
        public string strBirim { get; set; }
        public decimal mnyBirimFiyat { get; set; }
        public bool blDurum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Is> tbl_Is { get; set; }
        public virtual tbl_Is_Grubu tbl_Is_Grubu { get; set; }
    }
}
