//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Mahal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Mahal()
        {
            this.tbl_Is = new HashSet<tbl_Is>();
        }
    
        public int intMahalId { get; set; }
        public int intUrunId { get; set; }
        public int intMahalTipId { get; set; }
        public string strMahalAdi { get; set; }
        public bool blDurum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Is> tbl_Is { get; set; }
        public virtual tbl_Mahal_Tipi tbl_Mahal_Tipi { get; set; }
        public virtual tbl_Urun tbl_Urun { get; set; }
    }
}
